version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    restart: always

  growi:
    image: weseek/growi:6
    container_name: growi
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo/growi
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.4  # ← ここを変更（最新ではなく4.4を指定）
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - growi
      - nextcloud
    restart: always

volumes:
  nextcloud_data:
  mongo_data:
